Repository meilisearch/meilisearch-dart, pull requests merged in 2022-05, with the labels that each got.

#153 Update all the package dependencies
  pubspec.lock
Labels: dependencies

#155 Fix broken cropLength test in search_test.dart
  test/search_test.dart
Labels: skip-changelog

#156 Add new search parameters highlightPreTag, highlightPostTag and cropMarker
  lib/src/index.dart
  lib/src/index_impl.dart
  test/search_test.dart
Labels: enhancement

#159 Update code-samples regarding the v0.27 changes
  .code-samples.meilisearch.yaml
Labels: documentation

#162 Fix syntax issue in the README.md
  README.md
Labels: skip-changelog

#160 Update version for the next release (v0.5.3)
  CHANGELOG.md
  README.md
  example/pubspec.lock
  example/pubspec.yaml
  lib/src/version.dart
  pubspec.yaml
Labels: skip-changelog
