Repository meilisearch/meilisearch-dart, pull requests merged in 2022-06, with the labels that each got.

#158 Add setup to dependabot
  .github/dependabot.yaml
Labels: dependencies

#167 Remove pubspec.lock
  .gitignore
  example/pubspec.lock
  pubspec.lock
Labels: skip-changelog, dependencies

#173 Remove getDumpStatus method
  .code-samples.meilisearch.yaml
  lib/src/client.dart
  lib/src/client_impl.dart
  test/dump_test.dart
Labels: breaking-change

#171 Improve pub spec score points
  analysis_options.yaml
  lib/src/http_request_impl.dart
  lib/src/tenant_token/generator.dart
  pubspec.yaml
  test/exceptions_test.dart
Labels: maintenance

#179 Add test for `filter` paramter with spaces
  test/search_test.dart
Labels: enhancement

#180 Tasks refactor
  lib/src/client.dart
  lib/src/client_impl.dart
  lib/src/client_task_impl.dart
  lib/src/index.dart
  lib/src/index_impl.dart
  lib/src/query_parameters/tasks_query.dart
  lib/src/result_task.dart
  lib/src/task_impl.dart
  test/get_client_stats_test.dart
  test/indexes_test.dart
Labels: breaking-change

#183 Add a type wrapper to the Indexes resources
  lib/src/client.dart
  lib/src/client_impl.dart
  lib/src/query_parameters/indexes_query.dart
  test/indexes_test.dart
  test/utils/client.dart
Labels: breaking-change

#184 Add a type wrapper to the documents resources
  lib/src/index.dart
  lib/src/index_impl.dart
  lib/src/query_parameters/documents_query.dart
  test/documents_test.dart
Labels: breaking-change

#186 Add ability to specify uid in the keys creation
  lib/src/client.dart
  lib/src/client_impl.dart
  test/get_keys_test.dart
Labels: enhancement

#188 Add dump creation test
  test/dump_test.dart
Labels: enhancement
