Repository meilisearch/meilisearch-dart, pull requests merged in 2023-02, with the labels that each got.

#238 Update the version for the next release (v0.7.1)
  CHANGELOG.md
  README.md
  example/pubspec.lock
  example/pubspec.yaml
  lib/src/version.dart
  pubspec.yaml
Labels: skip-changelog

#240 Add indexUid to Task
  lib/src/query_parameters/cancel_tasks_query.dart
  lib/src/query_parameters/delete_tasks_query.dart
  lib/src/query_parameters/tasks_query.dart
  lib/src/task.dart
  test/dump_test.dart
  test/indexes_test.dart
Labels: enhancement, breaking-change

#241 Force CI break when library does not support all the platforms
  .github/workflows/tests.yml
  bors.toml
  test/web/base_test.dart
Labels: enhancement

#244 Add exported files to the meilisearch.dart
  .code-samples.meilisearch.yaml
  lib/meilisearch.dart
  lib/src/query_parameters/tasks_query.dart
  lib/src/searchable.dart
  test/documents_test.dart
  test/exceptions_test.dart
  test/get_keys_test.dart
  test/indexes_test.dart
  test/search_test.dart
  test/swaps_test.dart
  test/tasks_test.dart
  test/utils/wait_for.dart
Labels: bug, documentation, breaking-change

#245 Update the version for the next release (v0.8.0)
  CHANGELOG.md
  README.md
  example/pubspec.lock
  example/pubspec.yaml
  lib/src/version.dart
  pubspec.yaml
Labels: skip-changelog

#250 Fix createKey with uid
  lib/src/client_impl.dart
  test/get_keys_test.dart
Labels: bug

#249 upgrade to dio 5 and enable strict lints
  .github/workflows/tests.yml
  analysis_options.yaml
  bors.toml
  example/pubspec.lock
  lib/src/client.dart
  lib/src/client_impl.dart
  lib/src/exception.dart
  lib/src/http_request.dart
  lib/src/http_request_impl.dart
  lib/src/index.dart
  lib/src/index_impl.dart
  lib/src/index_settings.dart
  lib/src/key.dart
  lib/src/paginated_search_result.dart
  lib/src/query_parameters/cancel_tasks_query.dart
  lib/src/query_parameters/delete_tasks_query.dart
  lib/src/query_parameters/documents_query.dart
  lib/src/query_parameters/indexes_query.dart
  lib/src/query_parameters/keys_query.dart
  lib/src/query_parameters/queryable.dart
  lib/src/query_parameters/tasks_query.dart
  lib/src/result.dart
  lib/src/search_result.dart
  lib/src/searchable.dart
  lib/src/stats.dart
  lib/src/swap_index.dart
  lib/src/task.dart
  lib/src/tasks_results.dart
  lib/src/tenant_token/exceptions.dart
  lib/src/tenant_token/generator.dart
  lib/src/version.dart
  pubspec.yaml
  test/exceptions_test.dart
  test/get_keys_test.dart
  test/queryable_test.dart
  test/search_test.dart
  test/settings_test.dart
  test/tenant_token_test.dart
  test/utils/client.dart
  test/utils/wait_for.dart
Labels: enhancement, breaking-change, dependencies

#257 don't set User-Agent on web
  lib/src/http_request_impl.dart
  lib/src/version.dart
  test/analytics_test.dart
Labels: bug
