Repository meilisearch/meilisearch-dart, pull requests merged in 2023-05, with the labels that each got.

#299 Refactor tests and allow concurrency
  .github/workflows/tests.yml
  CONTRIBUTING.md
  example/pubspec.lock
  lib/src/swap_index.dart
  test/analytics_test.dart
  test/custom_dio_test.dart
  test/dump_test.dart
  test/exceptions_test.dart
  test/get_client_stats_test.dart
  test/get_keys_test.dart
  test/get_version_test.dart
  test/health_test.dart
  test/indexes_test.dart
  test/models/adapter.dart
  test/models/adapter_browser.dart
  test/models/adapter_io.dart
  test/models/test_client.dart
  test/queryable_test.dart
  test/search_test.dart
  test/settings_test.dart
  test/swaps_test.dart
  test/tasks_test.dart
  test/tenant_token_test.dart
  test/utils/books.dart
  test/utils/client.dart
  test/utils/wait_for.dart
Labels: enhancement

#304 Add screenshot
  analysis_options.yaml
  example/pubspec.lock
  pubspec.yaml
  screenshots/logo.png
Labels: maintenance

#307 Raise min Dart SDK to 3.0.0
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  CONTRIBUTING.md
  bors.toml
  example/pubspec.lock
  example/pubspec.yaml
  pubspec.yaml
Labels: breaking-change

#311 Remove useless message from README.md
  README.md
Labels: documentation, maintenance

#314 ensure lints resolves to the latest version 2.1.0
  pubspec.yaml
Labels: maintenance

#316 Remove _impl files
  lib/src/client.dart
  lib/src/client_impl.dart
  lib/src/http_request.dart
  lib/src/http_request_impl.dart
  lib/src/index.dart
  lib/src/index_impl.dart
  test/models/test_client.dart
Labels: maintenance
